### ISSUE TITLE
list_for_each_entry_rcu() vs list_for_each_entry()

### ISSUE THREAD

**Issue by cyring** [jinb-park/rcu_example#2]
Hello, thank you for this example.
Why `list_for_each_entry_rcu()` vs `list_for_each_entry()` in some functions ?

**Comment by jinb-park** [comment]
There was a mistake...
I should have used list_for_each_entry_rcu() for iterating rcu list.
Thanks for pointing it!

**Comment by cyring** [comment]
Thank you for this confirmation.
